name: Feature Request
description: Suggest a new idea or improvement
title: "[FEATURE]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill this out.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the feature.
      placeholder: I would like the system to...

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important?
      placeholder: This will help because...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered other solutions?
