name: CI - Lint, Test & Build

on:
  # Run automatically on PRs
  pull_request:
    branches: [ "main" ]

  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Lint check (will stop workflow on error)
      - name: Run Linter
        run: npm run lint

      # Run tests (optional for now)
      - name: Run Tests
        run: npm run test

      # Build project (runs only if lint & test pass)
      - name: Build Project
        run: npm run build
